### PR TITLE
Og talks html

### PR DESCRIPTION
**Pull request by jluis**
The html of the Twitter cards for the talks ( the two unapproved ones are also on my local branch)

### CODE REVIEW

**Comment by meis** [comment]
@alexm said something about making the permanent url http://friends.barcelona.pm/2017 and not only /. If we do the change, we'll have to change all the links and absolute references too.

**Comment by meis** [comment]
Apart from that, the three PR look good to me, but we should accept them in order and alltogether (i'd say #10, #11, #12) because they will get published as soon as they are in `master`.

**Comment by meis** [comment]
Just realized we have to strip the '.html' part too. The substitution should look like:
```
    <script>                                                                    
       window.location = window.location.pathname                               
        .replace(/\/talks\//,'#/talks/')                                        
        .replace(/\.html/,'');                                                  
    </script>   
```

**Comment by jluis** [comment]
It is not necessary if you don't type the html part of the url but I'll rewrite the script  to work well in this case too

El 15 de octubre de 2017 22:17:10 CEST, Marc Egea i Sala <notifications@github.com> escribió:
>Just realized we have to strip the '.html' part too. The substitution
>should look like:
>```
><script>                                                               
>    
>window.location = window.location.pathname                             
> 
>.replace(/\/talks\//,'#/talks/')                                       
>
>.replace(/\.html/,'');                                                 
>
>    </script>   
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/barcelonapm/perl-and-friends-2017/pull/12#issuecomment-336738357

-- 
Sent from my Android dee with K-9 Mail. Please excuse my brevity.

**Comment by jluis** [comment]
El diumenge, 15 d’octubre de 2017, a les 16:18:45 CEST, Marc Egea i Sala va escriure:
> @alexm said something about making the permanent url
> http://friends.barcelona.pm/2017 and not only /. If we do the change,
> we'll have to change all the links and absolute references too.

I think that we can do it later as the change can be made with perl -i -pe 's|(/images/)|/2017$1|g' and afer the event we wont need most of the material ( the paths ending in  'talks')

**Comment by alexm** [comment]
If we don't want permalinks there's no need to change anything after the event. We just remove everything the next time because links would end up broken anyway.

**Pull request merged**
