### PR TITLE
Explain the project purpose

### PR DESCRIPTION
**Pull request by alexm**
Adding a brief history of the event and some build instructions.

### CODE REVIEW

**Comment by alexm** [comment]
#68 fixes the missing carton command bug. This PR can be merged after that.

**Comment by meis** [comment]
I would not have documented how the build works* but I'm ok with the README if you guys like it.

* I really don't want to start a conversation about this now. Again, this is probably better talked in person, in a bar, with beers

**Comment by alexm** [comment]
> I would not have documented how the build works* but I'm ok with the README if you guys like it.

Maybe it'd be better to have the build instructions on their own `2018/_src/README` and leave the rest as it is or we can improve the build, so we don't need any instructions at all.

I'm OK with removing the build steps and move them somewhere else.

**Comment by alexm** [comment]
Build instructions removed, so #68 is no longer blocking this change.

**Pull request merged**
